gogs:
  image: gogs/gogs:v0.9.13
  ports:
    - ${http_port}:3000
    - ${ssh_port}:22
  links:
    - mysql:db
  volumes:
    - ${gogs_volume}:/data

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
      MYSQL_DATABASE: ${mysql_database}
      MYSQL_USER: ${mysql_user}
      MYSQL_PASSWORD: ${mysql_password}

